### ISSUE TITLE
I think there is something wrong with the updates you have done

### ISSUE THREAD

**Issue by behnampmdg3** [Ontraport/SDK-PHP#1]
A PHP Error was encountered

Severity: Notice

Message: Only variables should be passed by reference

Filename: src/APIAutoloader.php

Line Number: 19

Backtrace:

File: /Applications/MAMPPRO/Sites/app.pum/SDK-PHP/src/APIAutoloader.php
Line: 19
Function: _error_handler

File: /Applications/MAMPPRO/Sites/app.pum/SDK-PHP/src/Ontraport.php
Line: 79
Function: spl_autoload_call

File: /Applications/MAMPPRO/Sites/app.pum/SDK-PHP/src/Ontraport.php
Line: 60
Function: setHttpClient

File: /Applications/MAMPPRO/Sites/app.pum/application/controllers/Update_views.php
Line: 13
Function: __construct

File: /Applications/MAMPPRO/Sites/app.pum/index.php
Line: 315
Function: require_once

**Comment by akent-op** [comment]
PHP is displaying a warning because the results of the explode() passed to the array_pop() function in APIAutoloader.php are not a real variable and therefore should not be passed by reference. Updating line 19 to the following:
```
$tmp = explode("\\", $className);
$className = array_pop($tmp);
```

**Comment by behnampmdg3** [comment]
Hey Arielle-ontraport;

Is this something you should update in the library?

**Comment by akent-op** [comment]
Hi there,

Yes, this fix just needs to be approved and I will update the library tomorrow and close out this issue!
