### ISSUE TITLE
saveOrUpdate not working with custom objects

### ISSUE THREAD

**Issue by jrebs** [Ontraport/SDK-PHP#11]
I am not certain that this is a bug necessarily, but I've just spent a little while trying to get some updates to push to our custom objects and have now got it working by using another method.

Suppose a custom object with an objectID of 10001 and an object with ID of 1 that I wish to update. We have a custom field on this custom object that uses the field identifier "f1570" and contains a free formed string. f1570 currently has a value of 2.

```
$params = array('id' => 1, 'f1570' => 10);
$client->custom(10001)->saveOrUpdate($params);
```

This returns a code:0, no errors and returns the object's data in the response but the f1570 value does not update.

```
$params = array('objectID' ='10001', 'id' => 1, 'f1570' => 10);
$client->object()->saveOrUpdate($params);
```

The above should also work, to my knowledge, but it also returns a code:0 with the object data and does not update the custom field as requested.

```
$params = array('id' => 1, 'f1570' => 10);
$client->custom(10001)->update($params);
```

The update method DOES change the field as desired, returning a smaller set of data as usual when updates occur. Is there a problem with the saveOrUpdate implementation on custom objects or is this not supposed to work for some intended reason?

**Comment by akent-op** [comment]
Hi Justin,

The way saveOrUpdate() is implemented is to accept a dataset without an ID and then use a unique field to decide whether an existing record should be updated or a new record created. For contacts, this unique field defaults to "email". For custom objects, if unique fields are defined for the object, these will be matched against. This is primarily used to avoid duplicate emails in contact records but could be used for certain cases with custom objects. 

However, it looks like you are passing in the ID for the custom object you want to update. In that case, I would recommend using a straight update(), as you have the ID already and are not matching on a unique field. This will be faster than the saveOrUpdate() function and better for your use case. Hope this helps!

Arielle

**Comment by jrebs** [comment]
Hi, Arielle. The motivation to use saveOrUpdate on these calls was to keep our integration code as lean and easy to develop and debug as possible (by reducing it down to as few different logic paths as practical). I hadn't considered that the saveOrUpdate functionality would be expected to be different from regular update, but I'll revise this code to use update when an id is known.

Thanks as always.
