### ISSUE TITLE
ONTRAforms

### ISSUE THREAD

**Issue by tillkruss** [Ontraport/SDK-PHP#17]
How can I retrieve and interact with ONTRAforms?

**Comment by akent-op** [comment]
Hi Till,

We do not have a great deal of functionality exposed for manipulating ONTRAforms (or really any of our forms) via our API. What we do have exposed is available in our Forms.php class. Primarily, you can retrieve them, and retrieve the object meta. We do have code samples for our forms class here: https://api.ontraport.com/doc/?php#forms. Let me know if there is anything else I can do to help.

Best,

Arielle

**Comment by tillkruss** [comment]
Thanks, Arielle! 

I really only want to retrieve the JavaScript embed codes via the API. Right now we're copying the script tags around and it's impossible to know what's what.

Being able to fetch the script tags would be great, similar to what you offer with the SmartForm HTML.

I'm refering to these tags:

```html
<script type='text/javascript' async='true' src='https://app.ontraport.com/js/ontraport/opt_assets/drivers/opf.js' data-opf-uid='p2c100000f100' data-opf-params='borderColor=#fff&borderSize=0px&embed=true&formHeight=1142&formWidth=589px&popPosition=mc&instance=n00000000'></script>
```

**Comment by akent-op** [comment]
Ah gotcha. OK. We don't have that specific endpoint enabled for ONTRAforms currently, but if you use the Forms::retrieveSingle method and grab the json_raw_object property from that response, you can json_decode that property and grab the mergedData from it. This should get you the script tags you want. I will note this as a feature request and look into wrapping this functionality better for ONTRAforms.

**Comment by tillkruss** [comment]
Amazing. I see that's giving me the actual HTML. Is there any way to get the `<script>` tags that I see under "Publish" on ontraport.com?

<img width="1113" alt="Screen Shot 2019-05-29 at 12 32 09 PM" src="https://user-images.githubusercontent.com/665029/58585529-ce5e8f00-820d-11e9-9940-fb0c79d8f53d.png">

**Comment by akent-op** [comment]
I see what you are saying. Sorry I misunderstood. We do not currently have an endpoint for this, but I can see its usefulness. I am going to look into this as a feature request.

**Comment by tillkruss** [comment]
How soon will this be implemented and how do we know when it is?

**Comment by akent-op** [comment]
Hi Till,

I just got approval from our product team to implement this. I unfortunately do not have an exact ETA for you, as i the ticket needs to go through our regular process. However, I will keep you posted here as far as status so you will know when it is incoming. Hope this helps! Let me know if there is anything else I can do for you.

Best,

Arielle

**Comment by tillkruss** [comment]
That's fantastic, thanks!

**Comment by akent-op** [comment]
Hi Till, 

This functionality is implemented and moving into the testing phase. I will let you know when it is scheduled for release.

Best,

Arielle

**Comment by tillkruss** [comment]
@arielle-ontraport: Any updates?

**Comment by akent-op** [comment]
Hey Till,

Sorry, not yet. Aiming to get this in the release sometime next week.

**Comment by akent-op** [comment]
Just an update: QA is almost done testing this, I will let you know when it gets merged in and has a firm release date.

**Comment by tillkruss** [comment]
Amazing! Just in time!

**Comment by akent-op** [comment]
OK, the release is nigh. Code was just merged and will be released on Tuesday.

**Comment by akent-op** [comment]
Code was released this morning. For the SDK, we wrapped the original retrieveSmartFormHTML function into retrieveFormHtml which you can use on ONTRAforms as well. Let me know if I can be of further assistance!

**Comment by tillkruss** [comment]
Thanks. Quick note: the method is called `retrieveFormHTML()`.
