### ISSUE TITLE
Setting IP address / location via API

### ISSUE THREAD

**Issue by tillkruss** [Ontraport/SDK-PHP#18]
We're trying to set the latest IP address for a contract via API. Is that possible? We don't see it referenced here: https://api.ontraport.com/doc/#update-a-contact

Or is there a field in the Smart- or Ontraforms to specific an IP address? It seems to be picked up automatically, but incorrect. It's getting the proxy's IP.

<img width="312" alt="Screen Shot 2019-06-11 at 3 28 05 PM" src="https://user-images.githubusercontent.com/665029/59311237-aafc0100-8c5d-11e9-8c2f-17c943815c5a.png">

**Comment by akent-op** [comment]
Hey Till,

Yes there is. Sorry, that seems to be an oversight in the documentation. If you set the field ip_addy_display in your PUT request to the contacts endpoint, that should do the job.

Arielle

**Comment by tillkruss** [comment]
Ah fantastic! Will that trigger a lookup of city, state and country? Or will that only happen if those fields are empty?

**Comment by akent-op** [comment]
Unfortunately when you set that field via the API, it does not trigger the lookup of other location fields.

**Comment by tillkruss** [comment]
Thanks!
