### ISSUE TITLE
How to construct externs query string - {object}//{field}

### ISSUE THREAD

**Issue by kennethllamasares** [Ontraport/SDK-PHP#24]
Hi, just want to ask regarding how to use the externs parameter, I've been checking the docs but it doesn't clearly says on how to construct the externs query string? If you could provide a sample it would be great as well, thanks.

**Comment by akent-op** [comment]
Hi there!

Sure. The externs parameter should be sent as a comma separated list. The external fields themselves are formatted parent_id_field//parent_data_field. For example, if you wanted to make a request to retrieve contacts, and you also wanted not just the ID of the owner, but the owner first name and last name, externs = owner//firstname,owner//lastname. If you are trying to use externs to retrieve custom objects fields, you need to retrieve the meta and look for fields with a data_type of "parent" (http://api.ontraport.com/doc/#parent). Those are the fields that will appear before the "//" delimiter, and any fields that you want to access in that related object will appear after the delimiter.

Here is an example using CURL:

curl -X GET --header 'Accept: application/json' --header 'Api-Appid: XXXX' --header 'Api-Key: XXXX' 'http://api.ontraport.com/1/Contacts?range=50&externs=owner%2F%2Ffirstname%2Cowner%2F%2Flastname&listFields=firstname%2Clastname'

And here is an example using the SDK:

$client = new Ontraport("XXXX","XXXXX");
$requestParams = array(
    "listFields" => "firstname,lastname,email",
    "externs"=> "owner//firstname,owner//lastname"
);
$response = $client->contact()->retrieveMultiple($requestParams);

I will make a ticket to improve the documentation for that, seems like an oversight. Let me know if you need anything else!

**Comment by kennethllamasares** [comment]
thank you very much your support is greatly appreciated!
