### ISSUE TITLE
Contacts saveOrUpdate

### ISSUE THREAD

**Issue by cmbibby** [Ontraport/SDK-PHP#28]
Hi, I'm having an issues with saveOrUpdate on the Contacts object.

Using this code here :
$payload = array (
  'owner' => '',
  'firstname' => 'Test',
  'lastname' => 'Unique',
  'email' => 'cmb22@cmbd.io',
  'address' => '',
  'city' => '',
  'f1666' => '133',
  'zip' => '5051',
  'f1665' => '',
  'office_phone' => '040404040404',
  'sms_number' => '040404040404',
  'f1699' => '',
  'f1700' => '',
  'n_lead_source' => '',
  'n_medium' => '',
  'n_campaign' => '',
  'n_term' => '',
  'n_content' => ''
);
$response = $this->ontraport->contact()->saveOrUpdate( $payload );

If the Contact does not exist, the record is created OK and the created contact is returned.

However if I subsequently try this on a payload that looks like :

$payload = array (
  'owner' => '',
  'firstname' => 'Test',
  'lastname' => 'Unique',
  'email' => 'cmb22@cmbd.io',
  'address' => '',
  'city' => '',
  'f1666' => '133',
  'zip' => '5051',
  'f1665' => '',
  'office_phone' => '0333333333',
  'sms_number' => '0333333333',
  'f1699' => '',
  'f1700' => '',
  'n_lead_source' => '',
  'n_medium' => '',
  'n_campaign' => '',
  'n_term' => '',
  'n_content' => ''
);

I get a response of : 

'Save failed!'

What I'm expecting to happen is this contact record to be updated with the new office_phone and sms_number and have the new object returned.

Appreciate any insight.

Thanks

**Comment by akent-op** [comment]
Hi Chris,

I would be happy to help. First I'd like to isolate whether this is an issue with the API request itself, or with the request being made by the SDK. Can you try recreating this issue on our live API documentation at api.ontraport.com/live and let me know if you receive the same error? 

Best,

Arielle

**Comment by cmbibby** [comment]
Thanks, Arielle. I can confirm it is working OK on the Live API.

**Comment by akent-op** [comment]
OK thank you. I will look into this and get back to you.

**Comment by akent-op** [comment]
The request is dying on update because "owner" is being explicitly blanked, and contacts require an owner field. When you are creating the contact, we are assigning it to the default owner if a falsey value is sent, but when updating we are actually trying to blank out that value. If you remove the blank owner from your request, or explicitly set it to the desired owner, your request should work. I will make a ticket to follow up with a more informative response for that case. Let me know if this works for you!

**Comment by cmbibby** [comment]
Thanks very much for your help, Arielle. I can confirm this has solved my issue. Thankyou.

**Comment by akent-op** [comment]
Great! Happy to help.
