### ISSUE TITLE
HTTP response codes are discarded

### ISSUE THREAD

**Issue by jrebs** [Ontraport/SDK-PHP#3]
From the API documentation, it seems that if the response code is not a json success response with "code":"0", then the HTTP response code is meant to be used to diagnose the result (according to "Error and response codes" section of the API docs).

As an example, when I use the sdk to do a retrieveIdByEmail lookup on an email that doesn't exist in our account yet, I get back a simple string: "Object type with email 'tester@example.com' does not exist.". 

It seems to me that the response code needs to be made available to the calling code. I can think of a few possible ways to go about it. Is this something that's already in the plans? I might have to come up with something on my end if it's not in the short term, in which case I'd be happy to hear your thoughts on the best implementation.

**Comment by akent-op** [comment]
Note that this issue was handled with this PR: https://github.com/Ontraport/SDK-PHP/pull/4. Closing out. Thanks!
