### ISSUE TITLE
No way to pull product information

### ISSUE THREAD

**Issue by jrebs** [Ontraport/SDK-PHP#8]
It seems that there is no way to interface with the products objects using the PHP SDK. If I had an objectID, I could use the objects() interface, but it seems like the Products are a little different than the other objects. This leads me to think we have to use the restful Products/Product controllers to interact with our products.

If my above summary is correct, I've created an initial commit adding a Ontraport->product() method and a related Products class which supports the basic Products rest actions. I haven't thoroughly tested it yet, and I didn't document possible keys because that can be taken from the published API docs by the developer, no need to duplicate, I think.

https://github.com/jrebs/SDK-PHP/commit/acc4324fe771df8e96a571df22c14874476eb0c6

I'd appreciate your comment on whether this is the right solution and, if not, what is, or suggest changes to the above to make it service-ready.

Thanks

**Comment by akent-op** [comment]
Hi Justin, yes, this is the correct solution. Our new API docs and PHP wrapper are currently focused around our most commonly used endpoints, and we plan to expand both in future updates. If you want to access other objects using the objects() interface but find yourself lacking an object type id, you can find them at [api.ontraport.com/live](https://api.ontraport.com/live) under the endpoint definition. 

![product](https://user-images.githubusercontent.com/28546309/32624099-144a5d44-c53d-11e7-9892-19f50348b3b4.png)

You can also make a call to GET /objects/meta without specifying an object type and retrieve the meta for all objects, which will include type. 

Hope this helps!

**Comment by jrebs** [comment]
That helps a great deal. I didn't think to look at the live api page for additional ObjectIDs. That will solve my needs. Thanks.

**Comment by akent-op** [comment]
Hi Justin, 

Thought I would let you know we just added an ObjectType class containing constants for object type IDs of objects exposed in our API, so hopefully this will simplify your process a bit.
